Initial implementation
ember-engines/engine-blueprint pull request #1
Opened 2017-06-06 14:03 UTC by mike183

Initial implementation for the "stand-alone" engine blueprint.

cc/ @rwjblue @trentmwillis

2017-06-06 14:55 UTC, mike183 commented
This should be ready for a review.

2017-06-06 15:01 UTC, rwjblue approved these changes

2017-06-06 15:35 UTC, stefanpenner requested changes

2017-06-06 15:35 UTC, stefanpenner commented on files/routable-files/index.js
> +/*jshint node:true*/
`'use strict';`

2017-06-06 15:35 UTC, stefanpenner commented on files/routable-files/index.js
> +  isDevelopingAddon: function() {
`isDevelopingAddon() { }`

and this should likely only be true if `in-repo`

2017-06-06 15:35 UTC, stefanpenner commented on files/routeless-files/index.js
> +/*jshint node:true*/
`'use strict';`

2017-06-06 15:35 UTC, stefanpenner commented on files/routeless-files/index.js
> +var EngineAddon = require('ember-engines/lib/engine-addon');
`const`

2017-06-06 15:35 UTC, stefanpenner commented on files/routeless-files/index.js
> +  isDevelopingAddon: function() {
same as above re: `isDevelopingAddon`

2017-06-06 15:35 UTC, stefanpenner commented on index.js
> +  generatePackageJson: function(options, isInstall) {
concise function

2017-06-06 15:49 UTC, mike183 commented on files/routable-files/index.js
> +/*jshint node:true*/
Added

2017-06-06 15:49 UTC, mike183 commented on files/routable-files/index.js
> +  isDevelopingAddon: function() {
Removed the `isDevelopingAddon` method.

2017-06-06 15:49 UTC, mike183 commented on files/routeless-files/index.js
> +/*jshint node:true*/
Added

2017-06-06 15:50 UTC, mike183 commented on files/routeless-files/index.js
> +var EngineAddon = require('ember-engines/lib/engine-addon');
Updated, and also in the `routable-files/index.js` file.

2017-06-06 15:50 UTC, mike183 commented on files/routeless-files/index.js
> +  isDevelopingAddon: function() {
Removed the `isDevelopingAddon` method.

2017-06-06 15:50 UTC, mike183 commented on index.js
> +  generatePackageJson: function(options, isInstall) {
Updated

2017-06-06 15:51 UTC, mike183 commented
Thanks for the review @stefanpenner, I believe I've addressed all of the issues you mentioned.

2017-06-07 03:10 UTC, trentmwillis requested changes
Overall looks good to me, just a bunch of minor things (some for my own education).

2017-06-07 03:10 UTC, trentmwillis commented on blueprints/engine-blueprint/index.js
> +  Create an "addon blueprint" that simply defers to our
Could we add a `TODO` marker to this comment block? Just so it is obvious that there is something incomplete with this.

2017-06-07 03:10 UTC, trentmwillis commented on blueprints/engine-blueprint/index.js
> +    this.name = 'ember-engines/engine-blueprint';
Potentially dumb question, can we not set these properties in the `MainBlueprint` and avoid the `init` altogether?

2017-06-07 03:10 UTC, trentmwillis commented on files/routable-files/index.js
> +  lazyLoading: <%= isLazy %><% } %>
Should this be updated to use the new object definition for `lazyLoading`? Same for the routeless engine blueprint as well.

2017-06-07 03:10 UTC, trentmwillis commented on files/routable-files/addon-config/environment.js
> +  var ENV = {
Can use `const` here I believe.

2017-06-07 03:10 UTC, trentmwillis commented on files/routeless-files/addon-config/environment.js
> +  var ENV = {
`const` here as well.

2017-06-07 08:56 UTC, mike183 commented on blueprints/engine-blueprint/index.js
> +  Create an "addon blueprint" that simply defers to our
Added

2017-06-07 09:01 UTC, mike183 commented on blueprints/engine-blueprint/index.js
> +    this.name = 'ember-engines/engine-blueprint';
I think this is all just work-around code that will be removed when the mentioned issue is resolved and this file is removed.

Though, I just copied this from the glimmer blueprint so I could be wrong. I guess @rwjblue will be able to answer if this should be moved or not.

2017-06-07 09:03 UTC, mike183 commented on files/routable-files/index.js
> +  lazyLoading: <%= isLazy %><% } %>
Updated. I was actually thinking about this just as I finished up for the day yesterday.

@trentmwillis / @rwjblue: Should we also update this in the `in-repo-engine` blueprint as well?

2017-06-07 09:03 UTC, mike183 commented on files/routable-files/addon-config/environment.js
> +  var ENV = {
Updated

2017-06-07 09:03 UTC, mike183 commented on files/routeless-files/addon-config/environment.js
> +  var ENV = {
Updated

2017-06-07 09:04 UTC, mike183 commented
Thanks @trentmwillis, I've addressed all of the issues you mentioned and also left a question for you regarding the `in-repo-engine` blueprint.

2017-06-07 13:51 UTC, rwjblue commented on files/routable-files/index.js
> +  lazyLoading: <%= isLazy %><% } %>
Yes, I think we should.

2017-06-07 14:27 UTC, mike183 commented on files/routable-files/index.js
> +  lazyLoading: <%= isLazy %><% } %>
PR'd: https://github.com/ember-engines/ember-engines/pull/430

2017-06-08 04:39 UTC, trentmwillis approved these changes
Looks good to me. The above comment doesn't need to block this from landing as it could be addressed when the other `TODO` is addressed as well.

2017-06-08 13:24 UTC, merged